vich_uploader:
  db_driver: orm
  mappings:
    dog_image:
      uri_prefix: /images/dogs
      upload_destination: '%kernel.project_dir%/public/images/dogs'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
